<?php

// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
?>

<?php
$helper = $this->helper('Magento\Search\Helper\Data');
$mpanelHelper = $this->helper('MGS\Mpanel\Helper\Data');
$disableSearchFull = $mpanelHelper->getStoreConfig('mpanel/catalogsearch/search_full_page');
?>

<div class="search-form <?php if($disableSearchFull):?>not-full<?php endif;?>">
	<div class="form-search">
		<button class="search-close" onclick="showHideFormSearch()"><i class="pe-7s-close"></i></button>
		<form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
			<input id="search"
			   data-mage-init='{"quickSearch":{
					"formSelector":"#search_mini_form",
					"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
					"destinationSelector":"#search_autocomplete"}
			   }'
			   type="text"
			   name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
			   value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
			   class="input-text form-control"
			   maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
			   placeholder="<?= __($mpanelHelper->wellcomePlaceholder()) ?>"
			   role="combobox"
			   aria-expanded="true"
			   aria-haspopup="false"
			   aria-autocomplete="both"
			   autocomplete="off"/>

			<button type="submit" title="<?php echo $block->escapeHtml(__('Search')) ?>" class="button">
				<i class="pe-7s-search"></i>
			</button>

			<?php echo $block->getChildHtml() ?>
		</form>
        <div class="hot-words">
            <a href="#">váy</a>
            <a href="#">đầm</a>
            <a href="#">áo sơ mi</a>
            <a href="#">sơ mi kiểu</a>
            <a href="#">quần short</a>
            <a href="#">sét đồ</a>
        </div>
	</div>
	<div class="actions-search">
		<button class="action-search" onclick="showHideFormSearch()"><i class="pe-7s-search"></i></button>
	</div>
</div>

<script type="text/javascript">
	function showHideFormSearch(){
		require([
		'jquery'
		], function(jQuery){
			(function($) {
				if($('.search-form').hasClass('not-full')){
					$('html').toggleClass('search-not-full');
				}
				$('html').toggleClass('search-open');
				setTimeout(focusSearchField, 500);
			})(jQuery);
		});
	}

	function focusSearchField(){
		require([
		'jquery'
		], function(jQuery){
			(function($) {
				$('#search_mini_form input#search').focus();
			})(jQuery);
		});
	}
</script>
